version: '3.8'

services:
  jenkins:
    build: ./jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

  web:
    build: ./webapp
    ports:
      - "80:5000"
    volumes:
      - ./webapp:/app
    networks:
      - appnet

    sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      ports:
        - "9000:9000"
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      networks:
        - appnet
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions


volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:

networks:
  appnet:

# 2f7d247f525c4c579d2abf8d1204fc18