name: Local SonarQube Scan

on:
  push:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Wait for SonarQube to be healthy
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do
            sleep 5
          done

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r web/requirements.txt
          pip install sonarqube-scanner

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=flask-app \
            -Dsonar.sources=./web \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.python.version=3.11 \
            -Dsonar.login=$SONAR_TOKEN



# 2f7d247f525c4c579d2abf8d1204fc18

# Sonarqube password is Password@123

# squ_d0caf2a09fecffdcf4b5696908924c29b8d61cbb