name: SonarQube Localhost Scan

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r web/requirements.txt

    - name: Start SonarQube in background
      run: |
        docker run -d --name sonarqube \
          -p 9000:9000 \
          -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
          sonarqube:community

    - name: Wait for SonarQube to be ready
      run: |
        echo "Waiting for SonarQube to be UP..."
        for i in {1..30}; do
          STATUS=$(curl -s http://localhost:9000/api/system/status | jq -r .status || echo "DOWN")
          echo "Current status: $STATUS"
          if [ "$STATUS" = "UP" ]; then
            echo "SonarQube is ready!"
            break 
          fi
          sleep 5
        done
    
    - name: Wait for SonarQube to be fully ready
      run: |
        echo "Waiting for SonarQube full readiness..."
        for i in {1..20}; do
          READY=$(curl -s -u admin:Password@123 http://localhost:9000/api/webservices/list | jq -r '.components | length' || echo "0")
          echo "API response components: $READY"
          if [ "$READY" -gt 0 ]; then
            echo "SonarQube is fully ready!"
            break
          fi
          sleep 5
        done


    - name: Install SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        export SONAR_SCANNER_OPTS="-Xmx512m"
        sonar-scanner \
          -Dsonar.projectKey=flask-app \
          -Dsonar.sources=web \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN \
          -X

# 2f7d247f525c4c579d2abf8d1204fc18

# Sonarqube password is Password@123

# squ_f6a4ca576ab9ef45a46d742bbdfdb832d4dc77d1