name: Flask Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Chromium and Python dependencies
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        pip install -r backend/requirements.txt

    - name: Start Flask App in Background
      working-directory: ./web
      run: |
        export FLASK_APP=app.py
        nohup flask run --host=127.0.0.1 --port=5000 &
        sleep 5

    - name: Lint JS files with ESLint
      run: |
        npm install -g eslint
        npx eslint web/**/*.js || exit 1

    - name: Run Password Testcase
      working-directory: ./web
      run: python test_selenium.py
